defaultPlacement: end
enableVersioning: true
handle: program
name: Program
propagationMethod: all
siteSettings:
  aafb4ab4-f661-4486-8571-0def4630ed2c: # Motherhood Reclaimed
    enabledByDefault: true
    hasUrls: true
    template: _pages/program
    uriFormat: program
type: single
